#############################################################################
# Makefile for building: FixationsCoder.app/Contents/MacOS/FixationsCoder
# Generated by qmake (2.01a) (Qt 4.8.1) on: Mon Aug 19 18:51:43 2013
# Project:  FixationsCoder.pro
# Template: app
# Command: /Applications/Qt/Desktop/Qt/4.8.1/gcc/bin/qmake -spec /Applications/Qt/Desktop/Qt/4.8.1/gcc/mkspecs/macx-g++ CONFIG+=release -o Makefile FixationsCoder.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -arch x86_64 -Xarch_x86_64 -mmacosx-version-min=10.5 -Wall -W $(DEFINES)
CXXFLAGS      = -pipe -O2 -arch x86_64 -Xarch_x86_64 -mmacosx-version-min=10.5 -Wall -W $(DEFINES)
INCPATH       = -I/Applications/Qt/Desktop/Qt/4.8.1/gcc/mkspecs/macx-g++ -I. -I/Applications/Qt/Desktop/Qt/4.8.1/gcc/lib/QtCore.framework/Versions/4/Headers -I/Applications/Qt/Desktop/Qt/4.8.1/gcc/include/QtCore -I/Applications/Qt/Desktop/Qt/4.8.1/gcc/lib/QtGui.framework/Versions/4/Headers -I/Applications/Qt/Desktop/Qt/4.8.1/gcc/include/QtGui -I/Applications/Qt/Desktop/Qt/4.8.1/gcc/include -I/Users/irati/Documents/MyDocuments/PhD/Grafix/code/GraFIX_mac_1680_1050/FixationCoderPlus/FixationsCoder/../../../Codes/libraries/armadillo-3.4.4 -I. -I. -F/Applications/Qt/Desktop/Qt/4.8.1/gcc/lib
LINK          = g++
LFLAGS        = -headerpad_max_install_names -arch x86_64 -Xarch_x86_64 -mmacosx-version-min=10.5
LIBS          = $(SUBLIBS) -F/Applications/Qt/Desktop/Qt/4.8.1/gcc/lib -L/Applications/Qt/Desktop/Qt/4.8.1/gcc/lib -L/Users/irati/Documents/MyDocuments/PhD/Grafix/code/GraFIX_mac_1680_1050/FixationCoderPlus/FixationsCoder/../../../Codes/libraries/armadillo-3.4.4/ -larmadillo -framework QtGui -L/usr/local/pgsql/lib -L/tmp/qt-stuff-85167/source/qt-everywhere-opensource-src-4.8.1/Desktop/Qt/4.8.1/gcc/lib -F/tmp/qt-stuff-85167/source/qt-everywhere-opensource-src-4.8.1/Desktop/Qt/4.8.1/gcc/lib -framework QtCore 
AR            = ar cq
RANLIB        = ranlib -s
QMAKE         = /Applications/Qt/Desktop/Qt/4.8.1/gcc/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
STRIP         = 
INSTALL_FILE  = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = $(COPY_FILE)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
export MACOSX_DEPLOYMENT_TARGET = 10.4

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp \
		MyConstants.cpp \
		MainButtonsWidget.cpp \
		Operations.cpp \
		ConfigDialog.cpp \
		ProjectDialog.cpp \
		VisualizationDialog.cpp \
		SmoothXYdialog.cpp \
		FixationDurationsDialog.cpp \
		InterpolationDialog.cpp \
		FixDurOperations.cpp \
		PackageObj.cpp \
		VisualizationSegmentsDialog.cpp \
		StatisticsDialog.cpp \
		HeatMapDialog.cpp \
		ExportDialog.cpp moc_mainwindow.cpp \
		moc_MainButtonsWidget.cpp \
		moc_ConfigDialog.cpp \
		moc_ProjectDialog.cpp \
		moc_VisualizationDialog.cpp \
		moc_SmoothXYdialog.cpp \
		moc_FixationDurationsDialog.cpp \
		moc_InterpolationDialog.cpp \
		moc_VisualizationSegmentsDialog.cpp \
		moc_StatisticsDialog.cpp \
		moc_HeatMapDialog.cpp \
		moc_ExportDialog.cpp
OBJECTS       = main.o \
		mainwindow.o \
		MyConstants.o \
		MainButtonsWidget.o \
		Operations.o \
		ConfigDialog.o \
		ProjectDialog.o \
		VisualizationDialog.o \
		SmoothXYdialog.o \
		FixationDurationsDialog.o \
		InterpolationDialog.o \
		FixDurOperations.o \
		PackageObj.o \
		VisualizationSegmentsDialog.o \
		StatisticsDialog.o \
		HeatMapDialog.o \
		ExportDialog.o \
		moc_mainwindow.o \
		moc_MainButtonsWidget.o \
		moc_ConfigDialog.o \
		moc_ProjectDialog.o \
		moc_VisualizationDialog.o \
		moc_SmoothXYdialog.o \
		moc_FixationDurationsDialog.o \
		moc_InterpolationDialog.o \
		moc_VisualizationSegmentsDialog.o \
		moc_StatisticsDialog.o \
		moc_HeatMapDialog.o \
		moc_ExportDialog.o
DIST          = /Applications/Qt/Desktop/Qt/4.8.1/gcc/mkspecs/common/unix.conf \
		/Applications/Qt/Desktop/Qt/4.8.1/gcc/mkspecs/common/mac.conf \
		/Applications/Qt/Desktop/Qt/4.8.1/gcc/mkspecs/common/gcc-base.conf \
		/Applications/Qt/Desktop/Qt/4.8.1/gcc/mkspecs/common/gcc-base-macx.conf \
		/Applications/Qt/Desktop/Qt/4.8.1/gcc/mkspecs/common/g++-base.conf \
		/Applications/Qt/Desktop/Qt/4.8.1/gcc/mkspecs/common/g++-macx.conf \
		/Applications/Qt/Desktop/Qt/4.8.1/gcc/mkspecs/qconfig.pri \
		/Applications/Qt/Desktop/Qt/4.8.1/gcc/mkspecs/modules/qt_webkit_version.pri \
		/Applications/Qt/Desktop/Qt/4.8.1/gcc/mkspecs/features/qt_functions.prf \
		/Applications/Qt/Desktop/Qt/4.8.1/gcc/mkspecs/features/qt_config.prf \
		/Applications/Qt/Desktop/Qt/4.8.1/gcc/mkspecs/features/exclusive_builds.prf \
		/Applications/Qt/Desktop/Qt/4.8.1/gcc/mkspecs/features/default_pre.prf \
		/Applications/Qt/Desktop/Qt/4.8.1/gcc/mkspecs/features/mac/default_pre.prf \
		/Applications/Qt/Desktop/Qt/4.8.1/gcc/mkspecs/features/release.prf \
		/Applications/Qt/Desktop/Qt/4.8.1/gcc/mkspecs/features/default_post.prf \
		/Applications/Qt/Desktop/Qt/4.8.1/gcc/mkspecs/features/mac/default_post.prf \
		/Applications/Qt/Desktop/Qt/4.8.1/gcc/mkspecs/features/mac/x86_64.prf \
		/Applications/Qt/Desktop/Qt/4.8.1/gcc/mkspecs/features/mac/objective_c.prf \
		/Applications/Qt/Desktop/Qt/4.8.1/gcc/mkspecs/features/warn_on.prf \
		/Applications/Qt/Desktop/Qt/4.8.1/gcc/mkspecs/features/qt.prf \
		/Applications/Qt/Desktop/Qt/4.8.1/gcc/mkspecs/features/unix/thread.prf \
		/Applications/Qt/Desktop/Qt/4.8.1/gcc/mkspecs/features/moc.prf \
		/Applications/Qt/Desktop/Qt/4.8.1/gcc/mkspecs/features/mac/rez.prf \
		/Applications/Qt/Desktop/Qt/4.8.1/gcc/mkspecs/features/mac/sdk.prf \
		/Applications/Qt/Desktop/Qt/4.8.1/gcc/mkspecs/features/resources.prf \
		/Applications/Qt/Desktop/Qt/4.8.1/gcc/mkspecs/features/uic.prf \
		/Applications/Qt/Desktop/Qt/4.8.1/gcc/mkspecs/features/yacc.prf \
		/Applications/Qt/Desktop/Qt/4.8.1/gcc/mkspecs/features/lex.prf \
		/Applications/Qt/Desktop/Qt/4.8.1/gcc/mkspecs/features/include_source_dir.prf \
		FixationsCoder.pro
QMAKE_TARGET  = FixationsCoder
DESTDIR       = 
TARGET        = FixationsCoder.app/Contents/MacOS/FixationsCoder

####### Custom Compiler Variables
QMAKE_COMP_QMAKE_OBJECTIVE_CFLAGS = -pipe \
		-O2 \
		-arch \
		x86_64 \
		-Xarch_x86_64 \
		-mmacosx-version-min=10.5 \
		-Wall \
		-W


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile FixationsCoder.app/Contents/PkgInfo FixationsCoder.app/Contents/Resources/empty.lproj FixationsCoder.app/Contents/Info.plist $(TARGET)

$(TARGET): ui_mainwindow.h ui_MainButtonsWidget.h ui_ConfigDialog.h ui_ProjectDialog.h ui_VisualizationDialog.h ui_SmoothXYdialog.h ui_FixationDurationsDialog.h ui_InterpolationDialog.h ui_VisualizationSegmentsDialog.h ui_StatisticsDialog.h ui_HeatMapDialog.h ui_ExportDialog.h $(OBJECTS)  
	@$(CHK_DIR_EXISTS) FixationsCoder.app/Contents/MacOS/ || $(MKDIR) FixationsCoder.app/Contents/MacOS/ 
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: FixationsCoder.pro  /Applications/Qt/Desktop/Qt/4.8.1/gcc/mkspecs/macx-g++/qmake.conf /Applications/Qt/Desktop/Qt/4.8.1/gcc/mkspecs/common/unix.conf \
		/Applications/Qt/Desktop/Qt/4.8.1/gcc/mkspecs/common/mac.conf \
		/Applications/Qt/Desktop/Qt/4.8.1/gcc/mkspecs/common/gcc-base.conf \
		/Applications/Qt/Desktop/Qt/4.8.1/gcc/mkspecs/common/gcc-base-macx.conf \
		/Applications/Qt/Desktop/Qt/4.8.1/gcc/mkspecs/common/g++-base.conf \
		/Applications/Qt/Desktop/Qt/4.8.1/gcc/mkspecs/common/g++-macx.conf \
		/Applications/Qt/Desktop/Qt/4.8.1/gcc/mkspecs/qconfig.pri \
		/Applications/Qt/Desktop/Qt/4.8.1/gcc/mkspecs/modules/qt_webkit_version.pri \
		/Applications/Qt/Desktop/Qt/4.8.1/gcc/mkspecs/features/qt_functions.prf \
		/Applications/Qt/Desktop/Qt/4.8.1/gcc/mkspecs/features/qt_config.prf \
		/Applications/Qt/Desktop/Qt/4.8.1/gcc/mkspecs/features/exclusive_builds.prf \
		/Applications/Qt/Desktop/Qt/4.8.1/gcc/mkspecs/features/default_pre.prf \
		/Applications/Qt/Desktop/Qt/4.8.1/gcc/mkspecs/features/mac/default_pre.prf \
		/Applications/Qt/Desktop/Qt/4.8.1/gcc/mkspecs/features/release.prf \
		/Applications/Qt/Desktop/Qt/4.8.1/gcc/mkspecs/features/default_post.prf \
		/Applications/Qt/Desktop/Qt/4.8.1/gcc/mkspecs/features/mac/default_post.prf \
		/Applications/Qt/Desktop/Qt/4.8.1/gcc/mkspecs/features/mac/x86_64.prf \
		/Applications/Qt/Desktop/Qt/4.8.1/gcc/mkspecs/features/mac/objective_c.prf \
		/Applications/Qt/Desktop/Qt/4.8.1/gcc/mkspecs/features/warn_on.prf \
		/Applications/Qt/Desktop/Qt/4.8.1/gcc/mkspecs/features/qt.prf \
		/Applications/Qt/Desktop/Qt/4.8.1/gcc/mkspecs/features/unix/thread.prf \
		/Applications/Qt/Desktop/Qt/4.8.1/gcc/mkspecs/features/moc.prf \
		/Applications/Qt/Desktop/Qt/4.8.1/gcc/mkspecs/features/mac/rez.prf \
		/Applications/Qt/Desktop/Qt/4.8.1/gcc/mkspecs/features/mac/sdk.prf \
		/Applications/Qt/Desktop/Qt/4.8.1/gcc/mkspecs/features/resources.prf \
		/Applications/Qt/Desktop/Qt/4.8.1/gcc/mkspecs/features/uic.prf \
		/Applications/Qt/Desktop/Qt/4.8.1/gcc/mkspecs/features/yacc.prf \
		/Applications/Qt/Desktop/Qt/4.8.1/gcc/mkspecs/features/lex.prf \
		/Applications/Qt/Desktop/Qt/4.8.1/gcc/mkspecs/features/include_source_dir.prf \
		/Applications/Qt/Desktop/Qt/4.8.1/gcc/lib/QtGui.framework/QtGui.prl \
		/Applications/Qt/Desktop/Qt/4.8.1/gcc/lib/QtCore.framework/QtCore.prl
	$(QMAKE) -spec /Applications/Qt/Desktop/Qt/4.8.1/gcc/mkspecs/macx-g++ CONFIG+=release -o Makefile FixationsCoder.pro
/Applications/Qt/Desktop/Qt/4.8.1/gcc/mkspecs/common/unix.conf:
/Applications/Qt/Desktop/Qt/4.8.1/gcc/mkspecs/common/mac.conf:
/Applications/Qt/Desktop/Qt/4.8.1/gcc/mkspecs/common/gcc-base.conf:
/Applications/Qt/Desktop/Qt/4.8.1/gcc/mkspecs/common/gcc-base-macx.conf:
/Applications/Qt/Desktop/Qt/4.8.1/gcc/mkspecs/common/g++-base.conf:
/Applications/Qt/Desktop/Qt/4.8.1/gcc/mkspecs/common/g++-macx.conf:
/Applications/Qt/Desktop/Qt/4.8.1/gcc/mkspecs/qconfig.pri:
/Applications/Qt/Desktop/Qt/4.8.1/gcc/mkspecs/modules/qt_webkit_version.pri:
/Applications/Qt/Desktop/Qt/4.8.1/gcc/mkspecs/features/qt_functions.prf:
/Applications/Qt/Desktop/Qt/4.8.1/gcc/mkspecs/features/qt_config.prf:
/Applications/Qt/Desktop/Qt/4.8.1/gcc/mkspecs/features/exclusive_builds.prf:
/Applications/Qt/Desktop/Qt/4.8.1/gcc/mkspecs/features/default_pre.prf:
/Applications/Qt/Desktop/Qt/4.8.1/gcc/mkspecs/features/mac/default_pre.prf:
/Applications/Qt/Desktop/Qt/4.8.1/gcc/mkspecs/features/release.prf:
/Applications/Qt/Desktop/Qt/4.8.1/gcc/mkspecs/features/default_post.prf:
/Applications/Qt/Desktop/Qt/4.8.1/gcc/mkspecs/features/mac/default_post.prf:
/Applications/Qt/Desktop/Qt/4.8.1/gcc/mkspecs/features/mac/x86_64.prf:
/Applications/Qt/Desktop/Qt/4.8.1/gcc/mkspecs/features/mac/objective_c.prf:
/Applications/Qt/Desktop/Qt/4.8.1/gcc/mkspecs/features/warn_on.prf:
/Applications/Qt/Desktop/Qt/4.8.1/gcc/mkspecs/features/qt.prf:
/Applications/Qt/Desktop/Qt/4.8.1/gcc/mkspecs/features/unix/thread.prf:
/Applications/Qt/Desktop/Qt/4.8.1/gcc/mkspecs/features/moc.prf:
/Applications/Qt/Desktop/Qt/4.8.1/gcc/mkspecs/features/mac/rez.prf:
/Applications/Qt/Desktop/Qt/4.8.1/gcc/mkspecs/features/mac/sdk.prf:
/Applications/Qt/Desktop/Qt/4.8.1/gcc/mkspecs/features/resources.prf:
/Applications/Qt/Desktop/Qt/4.8.1/gcc/mkspecs/features/uic.prf:
/Applications/Qt/Desktop/Qt/4.8.1/gcc/mkspecs/features/yacc.prf:
/Applications/Qt/Desktop/Qt/4.8.1/gcc/mkspecs/features/lex.prf:
/Applications/Qt/Desktop/Qt/4.8.1/gcc/mkspecs/features/include_source_dir.prf:
/Applications/Qt/Desktop/Qt/4.8.1/gcc/lib/QtGui.framework/QtGui.prl:
/Applications/Qt/Desktop/Qt/4.8.1/gcc/lib/QtCore.framework/QtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec /Applications/Qt/Desktop/Qt/4.8.1/gcc/mkspecs/macx-g++ CONFIG+=release -o Makefile FixationsCoder.pro

FixationsCoder.app/Contents/PkgInfo: 
	@$(CHK_DIR_EXISTS) FixationsCoder.app/Contents || $(MKDIR) FixationsCoder.app/Contents 
	@$(DEL_FILE) FixationsCoder.app/Contents/PkgInfo
	@echo "APPL????" >FixationsCoder.app/Contents/PkgInfo
FixationsCoder.app/Contents/Resources/empty.lproj: 
	@$(CHK_DIR_EXISTS) FixationsCoder.app/Contents/Resources || $(MKDIR) FixationsCoder.app/Contents/Resources 
	@touch FixationsCoder.app/Contents/Resources/empty.lproj
	
FixationsCoder.app/Contents/Info.plist: 
	@$(CHK_DIR_EXISTS) FixationsCoder.app/Contents || $(MKDIR) FixationsCoder.app/Contents 
	@$(DEL_FILE) FixationsCoder.app/Contents/Info.plist
	@sed -e "s,@SHORT_VERSION@,1.0,g" -e "s,@TYPEINFO@,????,g" -e "s,@ICON@,,g" -e "s,@EXECUTABLE@,FixationsCoder,g" -e "s,@TYPEINFO@,????,g" /Applications/Qt/Desktop/Qt/4.8.1/gcc/mkspecs/macx-g++/Info.plist.app >FixationsCoder.app/Contents/Info.plist
dist: 
	@$(CHK_DIR_EXISTS) .tmp/FixationsCoder1.0.0 || $(MKDIR) .tmp/FixationsCoder1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/FixationsCoder1.0.0/ && $(COPY_FILE) --parents mainwindow.h MyConstants.h MainButtonsWidget.h Operations.h ConfigDialog.h ProjectDialog.h VisualizationDialog.h SmoothXYdialog.h FixationDurationsDialog.h InterpolationDialog.h FixDurOperations.h PackageObj.h VisualizationSegmentsDialog.h StatisticsDialog.h HeatMapDialog.h ExportDialog.h .tmp/FixationsCoder1.0.0/ && $(COPY_FILE) --parents main.cpp mainwindow.cpp MyConstants.cpp MainButtonsWidget.cpp Operations.cpp ConfigDialog.cpp ProjectDialog.cpp VisualizationDialog.cpp SmoothXYdialog.cpp FixationDurationsDialog.cpp InterpolationDialog.cpp FixDurOperations.cpp PackageObj.cpp VisualizationSegmentsDialog.cpp StatisticsDialog.cpp HeatMapDialog.cpp ExportDialog.cpp .tmp/FixationsCoder1.0.0/ && $(COPY_FILE) --parents mainwindow.ui MainButtonsWidget.ui ConfigDialog.ui ProjectDialog.ui VisualizationDialog.ui SmoothXYdialog.ui FixationDurationsDialog.ui InterpolationDialog.ui VisualizationSegmentsDialog.ui StatisticsDialog.ui HeatMapDialog.ui ExportDialog.ui .tmp/FixationsCoder1.0.0/ && (cd `dirname .tmp/FixationsCoder1.0.0` && $(TAR) FixationsCoder1.0.0.tar FixationsCoder1.0.0 && $(COMPRESS) FixationsCoder1.0.0.tar) && $(MOVE) `dirname .tmp/FixationsCoder1.0.0`/FixationsCoder1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/FixationsCoder1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) -r FixationsCoder.app
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_objective_c_make_all:
compiler_objective_c_clean:
compiler_moc_header_make_all: moc_mainwindow.cpp moc_MainButtonsWidget.cpp moc_ConfigDialog.cpp moc_ProjectDialog.cpp moc_VisualizationDialog.cpp moc_SmoothXYdialog.cpp moc_FixationDurationsDialog.cpp moc_InterpolationDialog.cpp moc_VisualizationSegmentsDialog.cpp moc_StatisticsDialog.cpp moc_HeatMapDialog.cpp moc_ExportDialog.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_MainButtonsWidget.cpp moc_ConfigDialog.cpp moc_ProjectDialog.cpp moc_VisualizationDialog.cpp moc_SmoothXYdialog.cpp moc_FixationDurationsDialog.cpp moc_InterpolationDialog.cpp moc_VisualizationSegmentsDialog.cpp moc_StatisticsDialog.cpp moc_HeatMapDialog.cpp moc_ExportDialog.cpp
moc_mainwindow.cpp: MyConstants.h \
		MainButtonsWidget.h \
		Operations.h \
		FixDurOperations.h \
		PackageObj.h \
		mainwindow.h
	/Applications/Qt/Desktop/Qt/4.8.1/gcc/bin/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ mainwindow.h -o moc_mainwindow.cpp

moc_MainButtonsWidget.cpp: MyConstants.h \
		MainButtonsWidget.h
	/Applications/Qt/Desktop/Qt/4.8.1/gcc/bin/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ MainButtonsWidget.h -o moc_MainButtonsWidget.cpp

moc_ConfigDialog.cpp: MyConstants.h \
		ConfigDialog.h
	/Applications/Qt/Desktop/Qt/4.8.1/gcc/bin/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ ConfigDialog.h -o moc_ConfigDialog.cpp

moc_ProjectDialog.cpp: ProjectDialog.h
	/Applications/Qt/Desktop/Qt/4.8.1/gcc/bin/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ ProjectDialog.h -o moc_ProjectDialog.cpp

moc_VisualizationDialog.cpp: MyConstants.h \
		VisualizationDialog.h
	/Applications/Qt/Desktop/Qt/4.8.1/gcc/bin/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ VisualizationDialog.h -o moc_VisualizationDialog.cpp

moc_SmoothXYdialog.cpp: SmoothXYdialog.h
	/Applications/Qt/Desktop/Qt/4.8.1/gcc/bin/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ SmoothXYdialog.h -o moc_SmoothXYdialog.cpp

moc_FixationDurationsDialog.cpp: FixDurOperations.h \
		PackageObj.h \
		MyConstants.h \
		FixationDurationsDialog.h
	/Applications/Qt/Desktop/Qt/4.8.1/gcc/bin/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ FixationDurationsDialog.h -o moc_FixationDurationsDialog.cpp

moc_InterpolationDialog.cpp: FixDurOperations.h \
		PackageObj.h \
		MyConstants.h \
		InterpolationDialog.h
	/Applications/Qt/Desktop/Qt/4.8.1/gcc/bin/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ InterpolationDialog.h -o moc_InterpolationDialog.cpp

moc_VisualizationSegmentsDialog.cpp: VisualizationSegmentsDialog.h
	/Applications/Qt/Desktop/Qt/4.8.1/gcc/bin/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ VisualizationSegmentsDialog.h -o moc_VisualizationSegmentsDialog.cpp

moc_StatisticsDialog.cpp: PackageObj.h \
		FixDurOperations.h \
		StatisticsDialog.h
	/Applications/Qt/Desktop/Qt/4.8.1/gcc/bin/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ StatisticsDialog.h -o moc_StatisticsDialog.cpp

moc_HeatMapDialog.cpp: HeatMapDialog.h
	/Applications/Qt/Desktop/Qt/4.8.1/gcc/bin/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ HeatMapDialog.h -o moc_HeatMapDialog.cpp

moc_ExportDialog.cpp: ExportDialog.h
	/Applications/Qt/Desktop/Qt/4.8.1/gcc/bin/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ ExportDialog.h -o moc_ExportDialog.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_uic_make_all: ui_mainwindow.h ui_MainButtonsWidget.h ui_ConfigDialog.h ui_ProjectDialog.h ui_VisualizationDialog.h ui_SmoothXYdialog.h ui_FixationDurationsDialog.h ui_InterpolationDialog.h ui_VisualizationSegmentsDialog.h ui_StatisticsDialog.h ui_HeatMapDialog.h ui_ExportDialog.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h ui_MainButtonsWidget.h ui_ConfigDialog.h ui_ProjectDialog.h ui_VisualizationDialog.h ui_SmoothXYdialog.h ui_FixationDurationsDialog.h ui_InterpolationDialog.h ui_VisualizationSegmentsDialog.h ui_StatisticsDialog.h ui_HeatMapDialog.h ui_ExportDialog.h
ui_mainwindow.h: mainwindow.ui
	/Applications/Qt/Desktop/Qt/4.8.1/gcc/bin/uic mainwindow.ui -o ui_mainwindow.h

ui_MainButtonsWidget.h: MainButtonsWidget.ui
	/Applications/Qt/Desktop/Qt/4.8.1/gcc/bin/uic MainButtonsWidget.ui -o ui_MainButtonsWidget.h

ui_ConfigDialog.h: ConfigDialog.ui
	/Applications/Qt/Desktop/Qt/4.8.1/gcc/bin/uic ConfigDialog.ui -o ui_ConfigDialog.h

ui_ProjectDialog.h: ProjectDialog.ui
	/Applications/Qt/Desktop/Qt/4.8.1/gcc/bin/uic ProjectDialog.ui -o ui_ProjectDialog.h

ui_VisualizationDialog.h: VisualizationDialog.ui
	/Applications/Qt/Desktop/Qt/4.8.1/gcc/bin/uic VisualizationDialog.ui -o ui_VisualizationDialog.h

ui_SmoothXYdialog.h: SmoothXYdialog.ui
	/Applications/Qt/Desktop/Qt/4.8.1/gcc/bin/uic SmoothXYdialog.ui -o ui_SmoothXYdialog.h

ui_FixationDurationsDialog.h: FixationDurationsDialog.ui
	/Applications/Qt/Desktop/Qt/4.8.1/gcc/bin/uic FixationDurationsDialog.ui -o ui_FixationDurationsDialog.h

ui_InterpolationDialog.h: InterpolationDialog.ui
	/Applications/Qt/Desktop/Qt/4.8.1/gcc/bin/uic InterpolationDialog.ui -o ui_InterpolationDialog.h

ui_VisualizationSegmentsDialog.h: VisualizationSegmentsDialog.ui
	/Applications/Qt/Desktop/Qt/4.8.1/gcc/bin/uic VisualizationSegmentsDialog.ui -o ui_VisualizationSegmentsDialog.h

ui_StatisticsDialog.h: StatisticsDialog.ui
	/Applications/Qt/Desktop/Qt/4.8.1/gcc/bin/uic StatisticsDialog.ui -o ui_StatisticsDialog.h

ui_HeatMapDialog.h: HeatMapDialog.ui
	/Applications/Qt/Desktop/Qt/4.8.1/gcc/bin/uic HeatMapDialog.ui -o ui_HeatMapDialog.h

ui_ExportDialog.h: ExportDialog.ui
	/Applications/Qt/Desktop/Qt/4.8.1/gcc/bin/uic ExportDialog.ui -o ui_ExportDialog.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp mainwindow.h \
		MyConstants.h \
		MainButtonsWidget.h \
		Operations.h \
		FixDurOperations.h \
		PackageObj.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		MyConstants.h \
		MainButtonsWidget.h \
		Operations.h \
		FixDurOperations.h \
		PackageObj.h \
		ui_mainwindow.h \
		ConfigDialog.h \
		ProjectDialog.h \
		VisualizationDialog.h \
		VisualizationSegmentsDialog.h \
		SmoothXYdialog.h \
		StatisticsDialog.h \
		HeatMapDialog.h \
		FixationDurationsDialog.h \
		InterpolationDialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

MyConstants.o: MyConstants.cpp MyConstants.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o MyConstants.o MyConstants.cpp

MainButtonsWidget.o: MainButtonsWidget.cpp MainButtonsWidget.h \
		MyConstants.h \
		ui_MainButtonsWidget.h \
		mainwindow.h \
		Operations.h \
		FixDurOperations.h \
		PackageObj.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o MainButtonsWidget.o MainButtonsWidget.cpp

Operations.o: Operations.cpp Operations.h \
		FixDurOperations.h \
		PackageObj.h \
		MyConstants.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Operations.o Operations.cpp

ConfigDialog.o: ConfigDialog.cpp ConfigDialog.h \
		MyConstants.h \
		ui_ConfigDialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ConfigDialog.o ConfigDialog.cpp

ProjectDialog.o: ProjectDialog.cpp ProjectDialog.h \
		ui_ProjectDialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ProjectDialog.o ProjectDialog.cpp

VisualizationDialog.o: VisualizationDialog.cpp VisualizationDialog.h \
		MyConstants.h \
		ui_VisualizationDialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o VisualizationDialog.o VisualizationDialog.cpp

SmoothXYdialog.o: SmoothXYdialog.cpp SmoothXYdialog.h \
		ui_SmoothXYdialog.h \
		MyConstants.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o SmoothXYdialog.o SmoothXYdialog.cpp

FixationDurationsDialog.o: FixationDurationsDialog.cpp FixationDurationsDialog.h \
		FixDurOperations.h \
		PackageObj.h \
		MyConstants.h \
		ui_FixationDurationsDialog.h \
		SmoothXYdialog.h \
		InterpolationDialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o FixationDurationsDialog.o FixationDurationsDialog.cpp

InterpolationDialog.o: InterpolationDialog.cpp InterpolationDialog.h \
		FixDurOperations.h \
		PackageObj.h \
		MyConstants.h \
		ui_InterpolationDialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o InterpolationDialog.o InterpolationDialog.cpp

FixDurOperations.o: FixDurOperations.cpp FixDurOperations.h \
		PackageObj.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o FixDurOperations.o FixDurOperations.cpp

PackageObj.o: PackageObj.cpp PackageObj.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o PackageObj.o PackageObj.cpp

VisualizationSegmentsDialog.o: VisualizationSegmentsDialog.cpp VisualizationSegmentsDialog.h \
		ui_VisualizationSegmentsDialog.h \
		MyConstants.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o VisualizationSegmentsDialog.o VisualizationSegmentsDialog.cpp

StatisticsDialog.o: StatisticsDialog.cpp StatisticsDialog.h \
		PackageObj.h \
		FixDurOperations.h \
		ui_StatisticsDialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o StatisticsDialog.o StatisticsDialog.cpp

HeatMapDialog.o: HeatMapDialog.cpp HeatMapDialog.h \
		ui_HeatMapDialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o HeatMapDialog.o HeatMapDialog.cpp

ExportDialog.o: ExportDialog.cpp ExportDialog.h \
		ui_ExportDialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ExportDialog.o ExportDialog.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_MainButtonsWidget.o: moc_MainButtonsWidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_MainButtonsWidget.o moc_MainButtonsWidget.cpp

moc_ConfigDialog.o: moc_ConfigDialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_ConfigDialog.o moc_ConfigDialog.cpp

moc_ProjectDialog.o: moc_ProjectDialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_ProjectDialog.o moc_ProjectDialog.cpp

moc_VisualizationDialog.o: moc_VisualizationDialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_VisualizationDialog.o moc_VisualizationDialog.cpp

moc_SmoothXYdialog.o: moc_SmoothXYdialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_SmoothXYdialog.o moc_SmoothXYdialog.cpp

moc_FixationDurationsDialog.o: moc_FixationDurationsDialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_FixationDurationsDialog.o moc_FixationDurationsDialog.cpp

moc_InterpolationDialog.o: moc_InterpolationDialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_InterpolationDialog.o moc_InterpolationDialog.cpp

moc_VisualizationSegmentsDialog.o: moc_VisualizationSegmentsDialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_VisualizationSegmentsDialog.o moc_VisualizationSegmentsDialog.cpp

moc_StatisticsDialog.o: moc_StatisticsDialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_StatisticsDialog.o moc_StatisticsDialog.cpp

moc_HeatMapDialog.o: moc_HeatMapDialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_HeatMapDialog.o moc_HeatMapDialog.cpp

moc_ExportDialog.o: moc_ExportDialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_ExportDialog.o moc_ExportDialog.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

