#include "MyConstants.h"

const double Consts::DEFAULT_SETTING_DEGREE_PER_PIXEL = 0.0177; // @1680 x 1050px at 90cm (48 x 30cm)
const double Consts::DEFAULT_SETTING_POSTHOC_MERGE_CONSECUTIVE_VAL = 0.25;
const double Consts::DEFAULT_SETTING_INTERP_MAXIMUM_DISPLACEMENT = 0.25;

const QString Consts::SETTING_PROJECT = "PROJECT";
const QString Consts::SETTING_HZ = "HZ";
const QString Consts::SETTING_EXP_WIDTH = "EXP_WIDTH";
const QString Consts::SETTING_EXP_HEIGHT = "EXP_HEIGHT";
const QString Consts::SETTING_DEGREE_PER_PIX = "DEGREE_PER_PIX";
const QString Consts::SETTING_SECS_FRAGMENT = "SECS_FRAGMENT";
const QString Consts::SETTINGS_CONFIGURATION_CHANGED_DATE =    "SETTINGS_CONFIGURATION_CHANGED_DATE";
const QString Consts::SETTING_INTERP_LATENCY=                  "SETTING_INTERP_LATENCY";
const QString Consts::SETTING_INTERP_VELOCITY_THRESHOLD=       "SETTING_INTERP_VELOCITY_THRESHOLD";
const QString Consts::SETTING_INTERP_MAXIMUM_DISPLACEMENT=     "SETTING_INTERP_MAXIMUM_DISPLACEMENT";
const QString Consts::SETTING_POSTHOC_MERGE_CONSECUTIVE_VAL=   "SETTING_POSTHOC_MERGE_CONSECUTIVE_VAL";
const QString Consts::SETTING_POSTHOC_MERGE_CONSECUTIVE_FLAG=  "SETTING_POSTHOC_MERGE_CONSECUTIVE_FLAG";
const QString Consts::SETTING_POSTHOC_LIMIT_RMS_VAL=           "SETTING_POSTHOC_LIMIT_RMS_VAL";
const QString Consts::SETTING_POSTHOC_LIMIT_RMS_FLAG=          "SETTING_POSTHOC_LIMIT_RMS_FLAG";
const QString Consts::SETTING_POSTHOC_MIN_DURATION_VAL=        "SETTING_POSTHOC_MIN_DURATION_VAL";
const QString Consts::SETTING_POSTHOC_MIN_DURATION_FLAG=       "SETTING_POSTHOC_MIN_DURATION_FLAG";


const QString Consts::PSETTING_ESTIMATED_FIX_DATE=  "PSETTING_ESTIMATED_FIX_DATE";
const QString Consts::PSETTING_INTERPOLATED_DATE=   "PSETTING_INTERPOLATED_DATE";
const QString Consts::PSETTING_SMOOTHED_DATE=       "PSETTING_SMOOTHED_DATE";
const QString Consts::PSETTING_NAME=                "PSETTING_NAME";
const QString Consts::PSETTING_ROUGH_PATH=          "PSETTING_ROUGH_PATH";
const QString Consts::PSETTING_SEGMENTS_PATH=       "PSETTING_SEGMENTS_PATH";
const QString Consts::PSETTING_NOTES=               "PSETTING_NOTES";
const QString Consts::PSETTING_CONFIGURATION=       "PSETTING_CONFIGURATION";
const QString Consts::PSETTING_LAST_SAVED_DATE=     "PSETTING_LAST_SAVED_DATE";
const QString Consts::PSETTING_CONFIGURATION_CHANGE_DATE= "PSETTING_CONFIGURATION_CHANGE_DATE";


const QString Consts::SETTING_SMOOTHING_SIGMA_S =              "SETTING_SMOOTHING_SIGMA_S";
const QString Consts::SETTING_SMOOTHING_SIGMA_R =              "SETTING_SMOOTHING_SIGMA_R";
const QString Consts::SETTING_SMOOTHING_USE_OTHER_EYE=         "SETTING_SMOOTH_USE_OTHER_EYE";
Consts::Consts(void)
{
}

